# 异常处理

```python
try:	
    #可能出现问题的代码
except Error1:
    #对Error1问题的解决方案
except Error2：
	#对Error2问题的解决方案
except BaseException as a:
    #对除开Error1和Error2之外的异常的解决方案，方案名为a。
    #a的值将会控制台报错时的异常的内容（Error：后面的内容）
    traceback.print_exc()	#打印错误信息，相当于控制台报错的全部输出
else:
    #当try中代码没有异常执行else中的代码
finally:
    #无论是否发生异常，finally中的代码总会被执行
```

> 当except后面直接冒号时，这个except必须在所有except的最后面